// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --linked > types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string
          name: string
          address: string | null
          phone: string | null
          email: string | null
          tax_rate: number
          currency: string
          settings: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          address?: string | null
          phone?: string | null
          email?: string | null
          tax_rate?: number
          currency?: string
          settings?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          address?: string | null
          phone?: string | null
          email?: string | null
          tax_rate?: number
          currency?: string
          settings?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          business_id: string
          full_name: string
          phone: string | null
          role: 'OWNER' | 'MANAGER' | 'STAFF' | 'HELPER'
          permissions: Json | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          business_id: string
          full_name: string
          phone?: string | null
          role?: 'OWNER' | 'MANAGER' | 'STAFF' | 'HELPER'
          permissions?: Json | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          full_name?: string
          phone?: string | null
          role?: 'OWNER' | 'MANAGER' | 'STAFF' | 'HELPER'
          permissions?: Json | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      categories: {
        Row: {
          id: string
          business_id: string
          name: string
          description: string | null
          parent_id: string | null
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          name: string
          description?: string | null
          parent_id?: string | null
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          name?: string
          description?: string | null
          parent_id?: string | null
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
      }
      items: {
        Row: {
          id: string
          business_id: string
          category_id: string | null
          name: string
          description: string | null
          price: number
          cost: number | null
          stock: number
          min_stock: number
          max_stock: number | null
          unit: string
          barcode: string | null
          sku: string | null
          image_url: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          category_id?: string | null
          name: string
          description?: string | null
          price: number
          cost?: number | null
          stock?: number
          min_stock?: number
          max_stock?: number | null
          unit?: string
          barcode?: string | null
          sku?: string | null
          image_url?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          category_id?: string | null
          name?: string
          description?: string | null
          price?: number
          cost?: number | null
          stock?: number
          min_stock?: number
          max_stock?: number | null
          unit?: string
          barcode?: string | null
          sku?: string | null
          image_url?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      customers: {
        Row: {
          id: string
          business_id: string
          name: string
          phone: string | null
          email: string | null
          address: string | null
          loyalty_points: number
          credit_limit: number
          credit_balance: number
          total_purchases: number
          last_visit: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          name: string
          phone?: string | null
          email?: string | null
          address?: string | null
          loyalty_points?: number
          credit_limit?: number
          credit_balance?: number
          total_purchases?: number
          last_visit?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          name?: string
          phone?: string | null
          email?: string | null
          address?: string | null
          loyalty_points?: number
          credit_limit?: number
          credit_balance?: number
          total_purchases?: number
          last_visit?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      sales: {
        Row: {
          id: string
          business_id: string
          sale_number: string
          customer_id: string | null
          user_id: string
          subtotal: number
          discount: number
          discount_type: string | null
          tax: number
          total: number
          status: 'COMPLETED' | 'PARKED' | 'CANCELLED'
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          sale_number?: string
          customer_id?: string | null
          user_id: string
          subtotal: number
          discount?: number
          discount_type?: string | null
          tax?: number
          total: number
          status?: 'COMPLETED' | 'PARKED' | 'CANCELLED'
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          sale_number?: string
          customer_id?: string | null
          user_id?: string
          subtotal?: number
          discount?: number
          discount_type?: string | null
          tax?: number
          total?: number
          status?: 'COMPLETED' | 'PARKED' | 'CANCELLED'
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      sale_items: {
        Row: {
          id: string
          sale_id: string
          item_id: string
          name: string
          quantity: number
          price: number
          discount: number
          tax: number
          total: number
        }
        Insert: {
          id?: string
          sale_id: string
          item_id: string
          name: string
          quantity: number
          price: number
          discount?: number
          tax?: number
          total: number
        }
        Update: {
          id?: string
          sale_id?: string
          item_id?: string
          name?: string
          quantity?: number
          price?: number
          discount?: number
          tax?: number
          total?: number
        }
      }
      payments: {
        Row: {
          id: string
          sale_id: string
          method: 'CASH' | 'CARD' | 'UPI' | 'WALLET'
          amount: number
          reference: string | null
          created_at: string
        }
        Insert: {
          id?: string
          sale_id: string
          method: 'CASH' | 'CARD' | 'UPI' | 'WALLET'
          amount: number
          reference?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          sale_id?: string
          method?: 'CASH' | 'CARD' | 'UPI' | 'WALLET'
          amount?: number
          reference?: string | null
          created_at?: string
        }
      }
      stock_movements: {
        Row: {
          id: string
          item_id: string
          business_id: string
          quantity: number
          type: 'IN' | 'OUT' | 'ADJUSTMENT'
          reason: string | null
          user_id: string
          reference: string | null
          created_at: string
        }
        Insert: {
          id?: string
          item_id: string
          business_id: string
          quantity: number
          type: 'IN' | 'OUT' | 'ADJUSTMENT'
          reason?: string | null
          user_id: string
          reference?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          item_id?: string
          business_id?: string
          quantity?: number
          type?: 'IN' | 'OUT' | 'ADJUSTMENT'
          reason?: string | null
          user_id?: string
          reference?: string | null
          created_at?: string
        }
      }
      expenses: {
        Row: {
          id: string
          business_id: string
          category: string
          amount: number
          description: string | null
          payment_method: string | null
          user_id: string
          date: string
          created_at: string
        }
        Insert: {
          id?: string
          business_id: string
          category: string
          amount: number
          description?: string | null
          payment_method?: string | null
          user_id: string
          date: string
          created_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          category?: string
          amount?: number
          description?: string | null
          payment_method?: string | null
          user_id?: string
          date?: string
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      user_role: 'OWNER' | 'MANAGER' | 'STAFF' | 'HELPER'
      sale_status: 'COMPLETED' | 'PARKED' | 'CANCELLED'
      payment_method: 'CASH' | 'CARD' | 'UPI' | 'WALLET'
      stock_movement_type: 'IN' | 'OUT' | 'ADJUSTMENT'
    }
  }
}

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']

// Convenience types
export type Business = Tables<'businesses'>
export type Profile = Tables<'profiles'>
export type Category = Tables<'categories'>
export type Item = Tables<'items'>
export type Customer = Tables<'customers'>
export type Sale = Tables<'sales'>
export type SaleItem = Tables<'sale_items'>
export type Payment = Tables<'payments'>
export type StockMovement = Tables<'stock_movements'>
export type Expense = Tables<'expenses'>

export type UserRole = Database['public']['Enums']['user_role']
export type SaleStatus = Database['public']['Enums']['sale_status']
export type PaymentMethod = Database['public']['Enums']['payment_method']
export type StockMovementType = Database['public']['Enums']['stock_movement_type']
